WVECKIDS ; WVEC KIDS Explorer Provider
 ;;3.0;WORLDVISTA ENGINEERING CONSOLE;;
 ;
EN ;
 D START^WVECNAV("WVECKIDS")
 Q
 ;
INIT ;
 K ^TMP($J,"WVECNAV","KIDS")
 S ^TMP($J,"WVECNAV","KIDS","MODE")="BUILDS"
 Q
 ;
BUILD ;
 N MODE
 D CLEAR^WVECWS
 S MODE=$G(^TMP($J,"WVECNAV","KIDS","MODE"),"BUILDS")
 I MODE="BUILDS" D BUILDBLDS Q
 I MODE="TYPES" D BUILDTYPES Q
 I MODE="ENTRIES" D BUILDENTS Q
 I MODE="DETAIL" D BUILDDET Q
 Q
 ;
BUILDBLDS ;
 N IEN,NAME,COUNT
 S COUNT=0,IEN=0
 F  S IEN=$O(^XPD(9.6,IEN)) Q:'IEN  D
 . S NAME=$P($G(^XPD(9.6,IEN,0)),U)
 . Q:NAME=""
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,NAME,"","BUILD",IEN)
 D SETSTATE^WVECWS("COUNT",COUNT)
 Q
 ;
BUILDTYPES ;
 N BUILD,FILE,COUNT,NAME
 S BUILD=+$G(^TMP($J,"WVECNAV","KIDS","BUILD"))
 S COUNT=0
 S FILE=0
 F  S FILE=$O(^XPD(9.6,BUILD,"KRN",FILE)) Q:'FILE  D
 . Q:'$D(^XPD(9.6,BUILD,"KRN",FILE))
 . S NAME=$$TYPENAME(FILE)
 . Q:NAME=""
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,NAME,"","TYPE",FILE)
 D SETSTATE^WVECWS("COUNT",COUNT)
 Q
 ;
BUILDENTS ;
 N BUILD,FILE,N,COUNT,X
 S BUILD=+$G(^TMP($J,"WVECNAV","KIDS","BUILD"))
 S FILE=+$G(^TMP($J,"WVECNAV","KIDS","FILE"))
 S COUNT=0,N=0
 F  S N=$O(^XPD(9.6,BUILD,"KRN",FILE,"NM",N)) Q:'N  D
 . S X=$G(^XPD(9.6,BUILD,"KRN",FILE,"NM",N,0))
 . Q:X=""
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,$P(X,U),"","ENTRY",N)
 D SETSTATE^WVECWS("COUNT",COUNT)
 Q
 ;
BUILDDET ;
 N BUILD,FILE,ENTRY,X
 S BUILD=+$G(^TMP($J,"WVECNAV","KIDS","BUILD"))
 S FILE=+$G(^TMP($J,"WVECNAV","KIDS","FILE"))
 S ENTRY=+$G(^TMP($J,"WVECNAV","KIDS","ENTRY"))
 S X=$G(^XPD(9.6,BUILD,"KRN",FILE,"NM",ENTRY,0))
 D ADDITEM^WVECWS(1,"Name: "_$P(X,U),"","PROP",$P(X,U))
 D ADDITEM^WVECWS(2,"Data: "_X,"","PROP",X)
 D SETSTATE^WVECWS("COUNT",2)
 Q
 ;
OPEN(NUMBER) ;
 N MODE,VALUE
 S MODE=$G(^TMP($J,"WVECNAV","KIDS","MODE"),"BUILDS")
 S VALUE=$$DATA^WVECWS(NUMBER)
 ;
 I MODE="BUILDS" D  Q
 . S ^TMP($J,"WVECNAV","KIDS","BUILD")=VALUE
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="TYPES"
 ;
 I MODE="TYPES" D  Q
 . S ^TMP($J,"WVECNAV","KIDS","FILE")=VALUE
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="ENTRIES"
 ;
 I MODE="ENTRIES" D  Q
 . S ^TMP($J,"WVECNAV","KIDS","ENTRY")=VALUE
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="DETAIL"
 ;
 Q
 ;
UP ;
 N MODE
 S MODE=$G(^TMP($J,"WVECNAV","KIDS","MODE"))
 ;
 I MODE="DETAIL" D  Q
 . K ^TMP($J,"WVECNAV","KIDS","ENTRY")
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="ENTRIES"
 ;
 I MODE="ENTRIES" D  Q
 . K ^TMP($J,"WVECNAV","KIDS","FILE")
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="TYPES"
 ;
 I MODE="TYPES" D  Q
 . K ^TMP($J,"WVECNAV","KIDS","BUILD")
 . S ^TMP($J,"WVECNAV","KIDS","MODE")="BUILDS"
 ;
 Q
 ;
TOP ;
 D INIT
 Q
 ;
REFRESH ;
 Q
 ;
HEADER ;
 N MODE,BUILD
 S MODE=$G(^TMP($J,"WVECNAV","KIDS","MODE"),"BUILDS")
 ;
 W @IOF
 W !,"============================================================"
 W !,"                  WVEC KIDS Explorer"
 W !,"============================================================"
 ;
 I MODE'="BUILDS" D
 . S BUILD=+$G(^TMP($J,"WVECNAV","KIDS","BUILD"))
 . W !,"Build: ",$P($G(^XPD(9.6,BUILD,0)),U)
 ;
 W !
 Q
 ;
TYPENAME(FILE) ;
 N NAME
 S NAME=$P($G(^DIC(FILE,0)),U)
 I NAME'="" Q NAME
 Q "KIDS Component"
 ;
VERSION() ;
 Q "3.0"
