WVECFM ; WorldVistA FileMan Explorer Provider
 ;;1.0;WORLDVISTA ENGINEERING CONSOLE;;
 ;
 ;---------------------------------------------------------
 ; WorldVistA Engineering Console
 ;
 ; FileMan Explorer Provider
 ;
 ; Provider Interface
 ;   EN
 ;   TITLE()
 ;   INIT()
 ;   LIST()
 ;   SELECT()
 ;   UP()
 ;   TOP()
 ;
 ;---------------------------------------------------------
 ;
EN ;
 Q
 ;
INIT ;
 K ^TMP($J,"WVECNAV","FM")
 S ^TMP($J,"WVECNAV","FM","MODE")="FILES"
 Q
BUILD ; Build Workspace
 N MODE

 D CLEAR^WVECWS

 S MODE=$G(^TMP($J,"WVECNAV","FM","MODE"),"FILES")

 I MODE="FILES" D BUILDFILES Q
 I MODE="FIELDS" D BUILDFIELDS Q
 I MODE="FIELD" D BUILDFIELD Q
 I MODE="COMPUTED" D BUILDCOMPUTED Q
 I MODE="REFS" D BUILDREFS Q
 Q
BUILDFILES ;
 N FILE,NAME,COUNT

 S COUNT=0
 S FILE=0

 F  S FILE=$O(^DIC(FILE)) Q:'FILE  D
 . S NAME=$P($G(^DIC(FILE,0)),U)
 . Q:NAME=""
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,NAME,"","FILE",FILE)

 D SETSTATE^WVECWS("COUNT",COUNT)

 Q
BUILDFIELDS ;
 N FILE,FIELD,COUNT,NAME,ZERO,TYPE,SUBFILE

 S FILE=+$G(^TMP($J,"WVECNAV","FM","FILE"))

 S COUNT=0
 S FIELD=0

 F  S FIELD=$O(^DD(FILE,FIELD)) Q:FIELD=""  D
 . Q:FIELD?1A.A
 . S ZERO=$G(^DD(FILE,FIELD,0))
 . S NAME=$P(ZERO,U)
 . Q:NAME=""
 . S TYPE=$P(ZERO,U,2)
 .
 . I TYPE?1.N.N.E,$D(^DD(+TYPE)) D
 . . S SUBFILE=+TYPE
 . . S NAME=NAME_" [MULTIPLE "_SUBFILE_"]"
 .
 . I TYPE["C" D
 . . S NAME=NAME_" [COMPUTED]"
 .
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,FIELD_"  "_NAME,"","FIELD",FIELD)

 D SETSTATE^WVECWS("COUNT",COUNT)

 Q
 ;
BUILDFIELD ;
 N FILE,FIELD,COUNT,NAME,ZERO,TYPE,LOC,TARGET

 S FILE=+$G(^TMP($J,"WVECNAV","FM","FILE"))
 S FIELD=$G(^TMP($J,"WVECNAV","FM","FIELD"))
 S ZERO=$G(^DD(FILE,FIELD,0))

 S COUNT=0

 S NAME=$P(ZERO,U)
 S COUNT=COUNT+1
 D ADDITEM^WVECWS(COUNT,"Name: "_NAME,"","PROP",NAME)

 S TYPE=$P(ZERO,U,2)
 S COUNT=COUNT+1
 D ADDITEM^WVECWS(COUNT,"Type: "_TYPE,"","PROP",TYPE)

 I TYPE["C" D
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,"Computed: YES","","PROP","YES")

 S LOC=$P(ZERO,U,4)
 S COUNT=COUNT+1
 D ADDITEM^WVECWS(COUNT,"Location: "_LOC,"","PROP",LOC)

 S COUNT=COUNT+1
 D ADDITEM^WVECWS(COUNT,"Field Number: "_FIELD,"","PROP",FIELD)

 I TYPE["C",$D(^DD(FILE,FIELD,9.1)) D
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,"Show Computed Logic","","COMPUTED",FIELD)
 I TYPE?1"P".N.E D
 . N TARGETNAME,REFCOUNT
 . S TARGET=+$E(TYPE,2,99)
 . S TARGETNAME=$P($G(^DIC(TARGET,0)),U)
 . I TARGETNAME'="" D
 . . S COUNT=COUNT+1
 . . D ADDITEM^WVECWS(COUNT,"Points To: "_TARGETNAME_" (#"_TARGET_")","","PROP",TARGET)
 . S REFCOUNT=$$REFBY^WVECFM(TARGET)
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,"Show References ("_REFCOUNT_")","","REFLIST",TARGET)
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,"Open File "_TARGET,"","POINTER",TARGET)

 I +TYPE>0,$D(^DD(+TYPE)) D
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,"Open Subfile "_(+TYPE),"","SUBFILE",+TYPE)

 D SETSTATE^WVECWS("COUNT",COUNT)

 Q
BUILDCOMPUTED ;
 N FILE,FIELD,COUNT,NODE

 S FILE=+$G(^TMP($J,"WVECNAV","FM","FILE"))
 S FIELD=$G(^TMP($J,"WVECNAV","FM","FIELD"))

 S COUNT=0

 F NODE=9.1:.1:9.9 D
 . Q:'$D(^DD(FILE,FIELD,NODE))
 . S COUNT=COUNT+1
 . D ADDITEM^WVECWS(COUNT,NODE_"  "_$G(^DD(FILE,FIELD,NODE)),"","PROP",NODE)

 D SETSTATE^WVECWS("COUNT",COUNT)

 Q
BUILDREFS ;
 N TARGET,SRC,FLD,TYP,COUNT,FILE0,FLD0

 S TARGET=+$G(^TMP($J,"WVECNAV","FM","TARGET"))
 S COUNT=0

 S SRC=0
 F  S SRC=$O(^DD(SRC)) Q:'SRC  D
 . S FLD=0
 . F  S FLD=$O(^DD(SRC,FLD)) Q:FLD=""  D
 . . S TYP=$P($G(^DD(SRC,FLD,0)),U,2)
 . . Q:'(TYP?1"P".N.E)
 . . Q:+$E(TYP,2,99)'=TARGET
 . .
 . . S FILE0=$P($G(^DIC(SRC,0)),U)
 . . S FLD0=$P($G(^DD(SRC,FLD,0)),U)
 . .
 . . S COUNT=COUNT+1
 . . D ADDITEM^WVECWS(COUNT,SRC_"  "_FILE0_"  "_FLD_"  "_FLD0,"","PROP",SRC_"^"_FLD)

 D SETSTATE^WVECWS("COUNT",COUNT)
 Q
 ;
UP ;
 N MODE

 S MODE=$G(^TMP($J,"WVECNAV","FM","MODE"))

 I MODE="COMPUTED" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELD"
 . D SETPAGE^WVECNAV(1)

 I MODE="REFS" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELD"
 . D SETPAGE^WVECNAV(1)

 I MODE="FIELD" D  Q
 . K ^TMP($J,"WVECNAV","FM","FIELD")
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELDS"
 . D SETPAGE^WVECNAV(1)

 I MODE="FIELDS",$D(^TMP($J,"WVECNAV","FM","PARENT")) D  Q
 . S ^TMP($J,"WVECNAV","FM","FILE")=^TMP($J,"WVECNAV","FM","PARENT")
 . K ^TMP($J,"WVECNAV","FM","PARENT")
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELDS"
 . D SETPAGE^WVECNAV(1)

 I MODE="FIELDS" D  Q
 . K ^TMP($J,"WVECNAV","FM","FILE")
 . S ^TMP($J,"WVECNAV","FM","MODE")="FILES"
 . D SETPAGE^WVECNAV(1)

 Q
TOP ;
 K ^TMP($J,"WVECNAV","FM")
 S ^TMP($J,"WVECNAV","FM","MODE")="FILES"
 Q
 ;
VERSION() ;
 Q "1.0"
 ;
HEADER ;
 N MODE,FILE,NAME

 S MODE=$G(^TMP($J,"WVECNAV","FM","MODE"),"FILES")

 W @IOF
 W !,"============================================================"
 W !,"                  WVEC FileMan Explorer"
 W !,"============================================================"

 I MODE="FIELDS" D
 . S FILE=$G(^TMP($J,"WVECNAV","FM","FILE"))
 . S NAME=$P($G(^DIC(FILE,0)),U)
 . W !,"File #: ",FILE,"   ",NAME

 W !
 Q
 ;
REFRESH ;
 Q
 ;
OPEN(NUMBER) ;
 N MODE,VALUE,ITEMTYPE

 S MODE=$G(^TMP($J,"WVECNAV","FM","MODE"),"FILES")
 S VALUE=$$DATA^WVECWS(NUMBER)
 S ITEMTYPE=$$TYPE^WVECWS(NUMBER)

 I ITEMTYPE="SUBFILE" D  Q
 . S ^TMP($J,"WVECNAV","FM","PARENT")=$G(^TMP($J,"WVECNAV","FM","FILE"))
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELDS"
 . S ^TMP($J,"WVECNAV","FM","FILE")=VALUE
 . K ^TMP($J,"WVECNAV","FM","FIELD")
 . D SETPAGE^WVECNAV(1)

 I ITEMTYPE="POINTER" D  Q
 . S ^TMP($J,"WVECNAV","FM","PARENT")=$G(^TMP($J,"WVECNAV","FM","FILE"))
 . K ^TMP($J,"WVECNAV","FM","FIELD")
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELDS"
 . S ^TMP($J,"WVECNAV","FM","FILE")=VALUE
 . D SETPAGE^WVECNAV(1)

 I ITEMTYPE="REFLIST" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="REFS"
 . S ^TMP($J,"WVECNAV","FM","TARGET")=VALUE
 . D SETPAGE^WVECNAV(1)

 I ITEMTYPE="COMPUTED" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="COMPUTED"
 . D SETPAGE^WVECNAV(1)

 I MODE="FILES" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELDS"
 . S ^TMP($J,"WVECNAV","FM","FILE")=VALUE
 . D SETPAGE^WVECNAV(1)

 I MODE="FIELDS" D  Q
 . S ^TMP($J,"WVECNAV","FM","MODE")="FIELD"
 . S ^TMP($J,"WVECNAV","FM","FIELD")=VALUE
 . D SETPAGE^WVECNAV(1)

 Q
 ;
FIND ; Find File or Field
 N MODE,TEXT,UPTEXT,MATCH,POS,FILE,NAME,FIELD,ZERO,I
 ;
 S MODE=$G(^TMP($J,"WVECNAV","FM","MODE"),"FILES")
 R !!,"Find: ",TEXT:300
 Q:TEXT=""
 ;
 S UPTEXT=$$UP^XLFSTR(TEXT)
 S MATCH=0
 S POS=0
 I MODE="FILES" D  Q
 . N FILEMATCH,ITEM
 . S FILEMATCH=0
 . S FILE=0
 . F  S FILE=$O(^DIC(FILE)) Q:'FILE  D  Q:FILEMATCH
 . . S NAME=$P($G(^DIC(FILE,0)),U)
 . . Q:NAME=""
 . . I (FILE=+TEXT)!(NAME[UPTEXT) S FILEMATCH=FILE
 . I 'FILEMATCH W !,"Not found." H 2 Q
 . S MATCH=0
 . S ITEM=0
 . F  S ITEM=$O(^TMP($J,"WVEC","LIST",ITEM)) Q:'ITEM  D  Q:MATCH
 . . I $$DATA^WVECWS(ITEM)=FILEMATCH S MATCH=ITEM
 . I 'MATCH W !,"File found but workspace item not located." H 2 Q
 . D SETPAGE^WVECNAV(((MATCH-1)\$$SIZE^WVECNAV())+1)
 . D OPEN^WVECFM(MATCH)
 . D SETDIRTY^WVECNAV(1)
 ;
 I MODE="FIELDS" D  Q
 . S FILE=+$G(^TMP($J,"WVECNAV","FM","FILE"))
 . Q:'FILE
 . S FIELD=0
 . F  S FIELD=$O(^DD(FILE,FIELD)) Q:FIELD=""  D  Q:MATCH
 . . Q:FIELD?1A.A
 . . S ZERO=$G(^DD(FILE,FIELD,0))
 . . S NAME=$P(ZERO,U)
 . . Q:NAME=""
 . . S POS=POS+1
 . . I (FIELD=TEXT)!(NAME[UPTEXT) S MATCH=FIELD
 . I 'MATCH W !,"Not found." H 2 Q
 . ;
 . ; Locate the matching workspace item.
 . S I=0
 . F  S I=$O(^TMP($J,"WVEC","LIST",I)) Q:'I  D  Q:MATCH=I
 . . I $$DATA^WVECWS(I)=FIELD S MATCH=I
 . I 'MATCH W !,"Field found but workspace item not located." H 2 Q
 . D SETPAGE^WVECNAV(((MATCH-1)\$$SIZE^WVECNAV())+1)
 . D OPEN^WVECFM(MATCH)
 . D SETDIRTY^WVECNAV(1)
 ;
 W !,"Find is not available in this mode." H 2
 Q

REFBY(FILE) ; Count fields pointing to FILE
 N SRC,FLD,TYP,COUNT

 S COUNT=0
 S SRC=0

 F  S SRC=$O(^DD(SRC)) Q:'SRC  D
 . S FLD=0
 . F  S FLD=$O(^DD(SRC,FLD)) Q:FLD=""  D
 . . S TYP=$P($G(^DD(SRC,FLD,0)),U,2)
 . . I TYP?1"P".N.E,+$E(TYP,2,99)=FILE S COUNT=COUNT+1

 Q COUNT
